sudo: false
language: java
jdk:
- oraclejdk8
services:
- mongodb
script:
- test/run.sh
notifications:
  slack:
    secure: LM9fzadH6D+7gUaxv05P/OHL0rVIDFHf27rXzuYx/CObMkpKpXseXR4Mug2l49WmeF12F/aXn1Zz8/7CY8NqkSS3qozRwHhtAqYVnwgCxN2h/eXPwenNRK2lMfTYMch6OWZo714MOHrW5Hqg3DZaIPnK3sB7OL5P+U6LRXjbtmA=
